### ISSUE TITLE
Uncaught Error: "disconnect" is a reserved event name

### ISSUE THREAD

**Issue by ghousetazeem** [meabhisingh/demo-cchat#1]
### While writing the the return function in chat.js i.e.:

`return()=>{
    socket.emit('disconnect');
    socket.off();
}`

It is showing the error at **socket.emit('disconnect')**

I think its because of the update in the **socket.io module**

**Comment by DheerajPaneru** [comment]
use socket.disconnect()

**Comment by ghousetazeem** [comment]
Thanks for the help. It worked
